### ISSUE TITLE
自动刷新喜加一出错

### ISSUE THREAD

**Issue by Cathgao** [half-ghost/steam_crawler_botV2#10]
```
[2022-10-27 23:23:00,013 stbot-喜加一] INFO: Scheduled job xjy_remind start.
[2022-10-27 23:23:00,075 stbot-喜加一] ERROR: <class 'json.decoder.JSONDecodeError'> occured when doing scheduled job xjy_remind.
[2022-10-27 23:23:00,075 stbot-喜加一] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\gaope\Desktop\HoshinoBot\hoshino\service.py", line 353, in wrapper
    ret = await func()
  File "C:\Users\gaope\Desktop\HoshinoBot\hoshino\modules\steam_crawler_botV2\xjy.py", line 197, in xjy_remind
    data = json.loads(f.read())
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by half-ghost** [comment]
参考 #9
