### ISSUE TITLE
风控时无法自动转为图片

### ISSUE THREAD

**Issue by dfmjndm** [half-ghost/steam_crawler_botV2#5]
send pic mes为false，但是风控时无法转图片，手动改为true可以发送

**Comment by half-ghost** [comment]
有日志截图吗，或者发送指令后，机器人是怎么回复的

**Comment by dfmjndm** [comment]
机器人没有回复，后台显示消息风控

**Comment by half-ghost** [comment]
> 机器人没有回复，后台显示消息风控

Hoshino端有<actionfailed, rercode=100>的报错吗

**Comment by dfmjndm** [comment]
有

[2022-04-21 18:03:19,636 stbot-steam] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when Gameinfo handling message -1.
2022-04-21 18:03:19 ERROR <class 'aiocqhttp.exceptions.ActionFailed'> occured when Gameinfo handling message -1.
[2022-04-21 18:03:19,637 stbot-steam] ERROR: <ActionFailed data=None, echo={'seq': 1}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "/hobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/hobot/hoshino/modules/steam_crawler_botV2/steam_crawler_botV2.py", line 115, in Gameinfo
    await bot.send(ev, "正在生成消息,请稍等片刻!", at_sender=True)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await

**Comment by half-ghost** [comment]
应该是修复了，可以再拉取新版本试试看
