### ISSUE TITLE
喜加一报错

### ISSUE THREAD

**Issue by SonderXiaoming** [half-ghost/steam_crawler_botV2#9]
[2022-06-03 04:34:00,001 stbot-喜加一] INFO: Scheduled job xjy_remind start.
[2022-06-03 04:34:00,173 stbot-喜加一] ERROR: <class 'json.decoder.JSONDecodeError'> occured when doing scheduled job xjy_remind.
[2022-06-03 04:34:00,173 stbot-喜加一] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\huannai\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\Users\Administrator\Desktop\huannai\hoshino\modules\steam_crawler_botV2\xjy.py", line 171, in xjy_remind
    data = json.loads(f.read())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by half-ghost** [comment]
这个应该是没爬取到数据源导致的，有可能是主机的网络问题，顺带问一句现在还会报错吗

**Comment by dfmjndm** [comment]
同一时间我这边也有这个报错

**Comment by half-ghost** [comment]
> 同一时间我这边也有这个报错

唔，那就怪了，我这边没问题，这个报错看起来是文件问题，文件里没数据，代码没问题的话应该就是网络问题了

**Comment by SonderXiaoming** [comment]
> 这个应该是没爬取到数据源导致的，有可能是主机的网络问题，顺带问一句现在还会报错吗

还会，感觉没好过（是不是要翻墙）

**Comment by half-ghost** [comment]
> > 这个应该是没爬取到数据源导致的，有可能是主机的网络问题，顺带问一句现在还会报错吗
> 
> 还会，感觉没好过（是不是要翻墙）

不用翻，数据源是国内的，it之家，我再看看怎么回事

**Comment by half-ghost** [comment]
> > 这个应该是没爬取到数据源导致的，有可能是主机的网络问题，顺带问一句现在还会报错吗
> 
> 还会，感觉没好过（是不是要翻墙）

唔，麻烦你进行这几步操作，1.看看data文件夹里的xjy_result.txt里边有没有内容，2.发送‘开启喜加一提醒’，bot有回复已开启的话，去看看xjy_result.txt里有没有记录你的群号，3.config.py里的代理项有填的话，看看steam或者小黑盒相关的指令能不能正确返回数据

**Comment by SonderXiaoming** [comment]
没有内容，没回复，报错好像和上面一样，代理没有，小黑盒特惠正常，steam搜标签正常

**Comment by half-ghost** [comment]
> 

那试试把原本的xjy_result.txt删掉，然后重新新建一个同名的文件，在里边填入这个 {"url": [], "groupid": []}，如果不是最新的话顺便也更新一下

**Comment by SonderXiaoming** [comment]
解决

**Comment by half-ghost** [comment]
> 解决

草，是更新了解决的还是重新新建解决的

**Comment by SonderXiaoming** [comment]
> > 解决
> 
> 草，是更新了解决的还是重新新建解决的

寄，我双管齐下的

**Comment by half-ghost** [comment]
> > > 解决
> > 
> > 
> > 草，是更新了解决的还是重新新建解决的
> 
> 寄，我双管齐下的

哈哈，也行
